### PR TITLE
Cleanup pom

### PR DESCRIPTION
**Pull request by nimsothea**

### CODE REVIEW

**Comment by jbarrera-xumak** [comment]
I got this error when I tested in my local environment.

`Failed to execute goal org.apache.sling:maven-sling-plugin:2.1.0:install (install-bundle) on project DantaAEMDemoBundle: Installation on http://localhost:4502/apps/dantademo/install failed, cause: Installation failed, cause: Conflict`

However the package is installed.

**Comment by nimsothea** [comment]
@jbarrera-xumak does "/apps/dantademo/install " exists in CRX?

**Comment by jbarrera-xumak** [comment]
When you install for the first time, that path will not exist.

**Comment by nimsothea** [comment]
I don't cannot see the error you encounter. What AEM version?

**Comment by jbarrera-xumak** [comment]
AEM 6.3

**Review by jbarrera-xumak — COMMENTED** [review]
This was done in another PR. #15

**Pull request closed without merging**
